version: 2

sources:

  - name: ecommerce
    database: fa--interview-task
    schema: interview
    tables:
      - name: orders
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
      - name: addresses
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
      - name: devices
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
      - name: payments
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
      - name: products
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
      - name: order_items
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}